// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using PrRag.Application.Domain;

#nullable disable

namespace PrRag.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PrRagDbContext))]
    partial class PrRagDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrRag.Application.Domain.PurchaseRequisition", b =>
                {
                    b.Property<string>("PurchaseRequisitionId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("purchase_requisition");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("supplier_code");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("supplier_name");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("character varying(28)")
                        .HasColumnName("item");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<float[]>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.HasKey("PurchaseRequisitionId");

                    b.ToTable("purchase_requisitions", (string)null);
                });

            modelBuilder.Entity("PrRag.Application.Domain.DataStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync");

                    b.HasKey("Id");

                    b.ToTable("data_status", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
